name: Deploy to Portainer

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ghcr.io

      - name: Build and Push docker image
        run: |
          docker build -t ghcr.io/s-triemer/my-image:latest .
          docker push ghcr.io/s-triemer/my-image:latest
      - name: Log in to Portainer
        run: docker login -u ${{ secrets.PORTAINER_USERNAME }}  -p ${{ secrets.DOCKER_PASSWORD }}  ${{ secrets.PORTAINER_HOST }}

      - name: Pull and Rebuild container in Portainer
        run: |
          docker pull ghcr.io/s-triemer/my-image:latest
          docker stop CONTAINER_NAME
          docker rm CONTAINER_NAME
          docker run -d --name CONTAINER_NAME -p 80:80 ghcr.io/s-triemer/my-image:latest
